Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "C:/Users/jonro/Desktop/shared_folder", "/home/vagrant/shared_folder"
  config.vm.provision "shell", path: 'provision.sh'
end