version: "3.9"
services:
        nginx:
                image: 'nginx'
                ports:
                        - "80:80"
        client:
                build: .
                command: [ "python", "./app.py", "http://35.189.202.84/" ]
                volumes:
                        - mi-vol:/data
volumes:
        mi-vol:
