apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
        - name: client
          image: jrodriguez225/as-entrega-individual
          command: [ "python", "./app.py", "http://34.116.181.171/" ]